---
title: "Collect some great adjectives"
output: pdf_document
---

Thank you for helping collect items for a new and improved Social Probabilistic Learning paradigm! If you don't know this task yet and are curious, you can look at a demo [here](http://cas-arcs.uoregon.edu/IRB_SPLIT/) (enter any number of participant ID and press "enter" for any blank screens). 

We're using this task to see if people learn a word-face association faster if the word is something that has to do with either **Status** or **Mate Seeking**, like "popular" or "dating", versus more neutral words like "hungry" and "thirsty". But that's pretty much all the words we have so far, which means that we can't be sure we'd get the same results if we were to use a different set of words. In an ideal experimental set-up, each participant would do this task using some smaller subset of a big pool of words that have to do with status, mate-seeking, or something less social and more mundane.

That's where you come in.

We need to come up with a list of single-word adjectives that are relevant to or somehow evoke mate-seeking and status motives, as well as words that are not really directly relevant to any other social motive (at least, systematically). For example, looking through one word list, I notice "abstinent" which I might tag as something possibly related to mate-seeking, "aggressive" as maybe relevant for status, and "abashed" as not really related to any social motive at all.

In coming up with our initial list, **the goal is to be exaustive, rather than precise**. That means, don't think too much -- if you see a word that seems like it might be a good fit, note it in the spreadsheet. We're going to do a second pass later with ratings for each word that should weed out what doesn't work well.

# Defining neutral, mate seeking, and status words

## Neutral

First, here are the eight social motives that I've taken status and mate-seeking from. For neutral words, you should avoid things that seem relevant to people who might care about these things:

- Self-protection
- Disease avoidance
- Affiliation
- Status
- Mate seeking
- Mate retention
- Care for one's onw children
- Care for family

## Mate seeking

There's no great description, in the papers I've uploaded, of the kinds of things that might be relevant to mate-seeking motives. Interestingly, a lot of things related to _stats_ are relevant for most people. I'm looking around for something better, but here's the guidance I can give you right now: look for adjectives that are pretty status-neutral but that might be important information when considering a possible long-term or short-term relationship partner. Like the above "is this person dating someone or looking for someone to date?" For example, "faithful" and "adulterous". Both these adjectives descibe tendencies in behavior that might be relevant to someone looking for a partner, and while they may be related to social status in some cultural contexts, it seems to me that they don't automatically convey social status. 

Use that, and your own intuition to guide your choices here.

## Status

From Kenrick et al. (2010):

> Maslow classified esteem needs
into two related sets—one consisting of desires for strength,
achievement, and mastery (which contributed to one’s selfesteem) and the other consisting of desires for reputation, status, dominance, and glory (or the esteem of others).

>Henrich and Gil-White (2001) note that status in humans
can arise from physical dominance and threat in the same way
that it typically does in other animals. They distinguish this
from prestige, which is freely conferred deference toward
individuals who possess special skills and information.

>A functional analysis also addresses
why people are motivated not only to attain status, but also
to defer to others who are high in status. If those others are physically dominant, deference reduces the odds of physical conflict; if they have information-based prestige, deference
increases the odds of learning from them (Henrich & GilWhite, 2001).

Use these ideas about status and your own intuition to pick out good words.

# The source material

1. Rebecca Neel's [Fundamental Social Motives Inventory](https://osf.io/jfm28/) is at the end of the linked paper.
    - This is the best place to go if you want to get a feel for the sorts of things we mean by status and mate-seeking motives. Feel free to riff off this questionnaire if certain adjectives come to mind.
1. [The international personality item pool](http://ipip.ori.org/newIndexofScaleLabels.htm)
    - Look just at the list of constructs and the scale names here. For example, at the top is "Achievement-striving (NEO: C4), (TCI: P3), (MPQ: AC), (6FPQ: IT1), (HPI: Competitive HIC)", so I might pull out both "striving" and "competitive" for status related adjectives. You can look at the items to get a feel for the concepts, but most are too long to use.
2. Allport and Odbert's [Trait-names](https://osf.io/t9kqb/)
    - There's a massive word list at the end of this document. This is the motherlode, and the best place I can think of for grabbing new words. It seems to me the "temporary states" words are perhaps best suited for the neutral category.
    
# The process

First, split up the source material. Here's an easy list to work from -- just do the constructs and words that start with these letters. And if one of you finishes early, grab stuff from the other.

```{r echo=F,message=F}
set.seed(41107)
random_letters <- sample(letters, size = length(letters))
knitr::kable(data.frame(
    Hannah = sort(random_letters[seq(1, 26,2)]),
    Morgan = sort(random_letters[seq(2, 26,2)])
))
```

Keep track of the words in [this spreadsheet](https://osf.io/5qm48/), which you can access by clicking "View this file on Google Drive" and signing in with some gmail account. If that doesn't work for you, please let me know.

As you start collecting what you think are good candidate words, I'll look through your lists and let you know if I spot any concerns. But again, we're going for bulk, not quality. 

Finally, we'll put these into a qualtrics questionnaire and get some ratings about what people think.

#THANK YOU SO MUCH FOR YOUR HELP!
